### ISSUE TITLE
Autocomplete for HTML tags in .twig files doesn’t work correctly in Nova 10+

### ISSUE THREAD

**Issue by DowleyDeveloped** [tpmatthes/Twig.novaextension#13] opened 2023-06-02 07:01 UTC
Hi!

First off, love this extension. 

However I've noticed since the update to Nova 11, the auto complete for tags has stopped working, even when autocomplete is selected within editing preferences.

Is this something that can be fixed?

**Comment by tpmatthes** [comment] 2023-06-03 10:50
Hey, thanks for submitting an issue! I’m glad you find this little extension helpful. 😄

I just tested autocomplete on Nova 11.1 and it seems like it’s working as intended:

<img width="536" alt="autocomplete" src="https://github.com/tpmatthes/Twig.novaextension/assets/30212990/fcf12467-1a90-463b-8896-fc62eadf14cf">

May I ask you for more details? Did autocomplete stopped working completely or is it realted to specific situations? Feel free to share some example files and/or screenshots to help me investigate.

**Comment by DowleyDeveloped** [comment] 2023-06-04 00:44
Ah apologies I meant Novas built in autocomplete for closing tags. For example in any language if I have an open div and I start typing </ it’ll automatically close the div. 

However with Nova 11, I’ve noticed this no longer works with the Twig / HTML language selected.

**Comment by tpmatthes** [comment] 2023-06-04 08:46
Ok, I see. I’ve tested autocomplete for HTML tags inside .twig files with Nova 9.6 and Nova 11.1 with the same version of my plugin installed. It works fine in Nova 9.6, but in Nova 11.1 only a small fraction of the built-in completions for HTML are being used.

Nova 10 introduced a new parsing system for language definitions (Tree-sitter), and they rewrote all the built-in languages and completions. The language definition for Twig used for this plugin is still regex-based. It refers to the built-in HTML definition which should work fine in theory. However, there are some problems with compatability, I guess.

Do you use any other plugins for languages that are based on HTML?

**Comment by DowleyDeveloped** [comment] 2023-06-04 08:49
Not currently, only Twig.

**Comment by tpmatthes** [comment] 2023-06-04 09:20
Ok, I’ll reach out to Panic (probably via a post on the Nova developer forum), and update this issue when I have more information. Thanks for your input!

**Comment by DowleyDeveloped** [comment] 2023-06-04 09:43
Brill, thank you!

**Comment by tpmatthes** [comment] 2023-06-08 19:10
Hey @DowleyDeveloped, the new completions bundled with the built-in languages (based on Tree-sitter) in Nova 10+ aren’t compatible with “old” regex-based languages anymore. That’s why HTML completions stopped working for you.

The Twig plugin is still regex-based and I don’t have time to migrate to Tree-sitter at the moment. However, it’s possible to bundle this plugin with the built-in completions for HTML from Nova 9.6 in the meantime.

I just released version 1.8.2 of my plugin which re-adds HTML completions for Twig files. Autocomplete for HTML tags still doesn’t work, but it seems like this is a bug on Panic’s end.

You can find more details here: https://devforum.nova.app/t/nova-10-completions-from-built-in-html-language-don-t-work-when-used-as-subsyntax-inside-regex-based-language-twig/2194

**Comment by DowleyDeveloped** [comment] 2023-06-09 06:55
Hi @tpmatthes 

Makes sense. Thanks for looking into it for me!

**Comment by TimE90** [comment] 2023-06-09 08:54
Same problem here!

What's the way to fix this / add autocomplete for tag closing again for now? @tpmatthes 

Because it's not working with new plugin version (as you already said) but that means the issue isn't fixed?
<img width="272" alt="image" src="https://github.com/tpmatthes/Twig.novaextension/assets/2539165/5a2c98a8-7520-45a6-b22f-d95d2808176e">

**Comment by tpmatthes** [comment] 2023-06-09 17:24
You’re right, autocomplete for HTML tags inside of Twig files still doesn’t work in Nova 10+. However, this function has never been provided by my plugin. I’m just including the built-in HTML syntax definition for HTML, so I (probably) can’t do much about it.

It seems like this is indeed a bug on Panic’s end:
> We’ve received other reports about autoclosing of tags in regex-based grammars not working as expected, and are looking into it.
— https://devforum.nova.app/t/nova-10-syntax-highlighting-broken-on-closing-tag-twig-plugin-regex/2164

I guess we have to wait until Panic addresses this. I’ll reopen this isssue, so other people can find it.

**Comment by DowleyDeveloped** [comment] 2023-06-13 07:34
@tpmatthes Looks like this has been fixed as part of Nova 11.2!

**Comment by tpmatthes** [comment] 2023-06-13 16:51
Thanks for leting me know! They did indeed fix it:

> Fixed: Autoclosing of tags in regex-based grammars now works as expected

🎉

**Closed as completed by tpmatthes** 2023-06-13 16:51 UTC
